### ISSUE TITLE
Repacking Sfar with Original Checksum.

### ISSUE THREAD

**Issue by romulus2k4** [ME3Tweaks/ME3Explorer-XENON#1]
Hello.

If I unpack the original default.sfar from the DLCs, and pack them back, is there anyway I can pack it back with the original hash for the default.sfar? I need this for backup purposes, as the .sfar format doesn't compress very well, but once extracted, it can be compressed to 45% of it's original size, or even less. But the only thing that's not sitting well with me is that once unpacked, then repacked as sfar, the DLCs lose their original checksum/hash and Origin insists on downloading them again. Any help would be appreciated.

**Comment by Mgamerz** [comment]
This project is for the Xbox xenon build and it is extract only. You can't
pack back a modified sfar with the original hash as that would mean the
file is unmodified.

**Comment by romulus2k4** [comment]
I wasn't aware that this project isn't meant for PC.

I am not trying to pack back a modified sfar. What I am trying to do is unpack a sfar, compress the files and store it in an optical medium, uncompress it upon installation, and then repack it into sfar while maintaining the original hash, as I have modified no content of the original sfar.

Thank you for taking the time to reply. Much appreciated.

**Comment by Mgamerz** [comment]
That is not possible as the compression algorithm is not  the exact same as
the one used by bioware, but compatible. Additionally, individual file
compression is worse than the default sfar compression. Another thing is
that all the tools for packing an sfar append and repoint, rather than
replacing existing entries.

If you need to split the sfars to optical media for transfer you can put it
into it into a winrar archive split and then split it to files. Then put
all the files back into the same directory and unrar it.
